package QA.UAT;

import java.awt.AWTException;
import java.io.File;

import javax.swing.JOptionPane;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.SearchContext;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.NoAlertPresentException;	
import org.openqa.selenium.Alert;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;




public class PosnetVW {
	
	
	public PosnetVW () {}
	

		
	
	public void Venta_VW_Bank_Nuevos (ChromeDriver controlador, String producto) throws Exception {
		
				
		System.out.println("-----------------------------------------");
		System.out.println("---------Ingresando a Posnet UAT---------");
		System.out.println("-----------------------------------------");
		controlador.get("https://cardifonline-uat.com.mx/posnet/login.jsf#");
		System.out.println("-----------------------------------------");
		File scrFile = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile, new File("d:\\Evidencias_Automatizacion\\Valora\\Inicio Login.png"));
		Thread.sleep(1000);
		System.out.println("----------Ingresando Usuario-------------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.name("j_idt26")).sendKeys("2014042829");
		Thread.sleep(1000);
		System.out.println("---------Ingresando Contraseña-----------");
		controlador.findElement(By.name("j_idt30")).sendKeys("Cardif123#");
		File scrFile01 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile01, new File("d:\\Evidencias_Automatizacion\\Valora\\Inicio Login.png"));
		controlador.findElement(By.id("j_idt34")).click();
		Thread.sleep(1500);
		System.out.println("-----------------------------------------");
		System.out.println("------------Conexion exitosa-------------");
		File scrFile1 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile1, new File("d:\\Evidencias_Automatizacion\\Valora\\Conexion_exitosa.png"));
		/*------------------------------- Cuenta Clabe ---------------------------------------*/
		System.out.println("-----------------------------------------");
		System.out.println("----------Seleccion de Producto----------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.xpath("//*[@id='frmWelcome']/div/table[1]/tbody/tr[1]/td/a/div")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmSelectProductos:selectProducto_label")).click();
		Thread.sleep(500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:selectProducto_panel']/div/ul/li[2]")).click();
		Thread.sleep(1500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:canalSocioCanalVenta']/tbody/tr[3]/td[1]/div/div[2]")).click();
		File scrFile2 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile2, new File("d:\\Evidencias_Automatizacion\\Valora\\Seleccion Producto.png"));
		Thread.sleep(1500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:cmdNext']/div")).click();
		Thread.sleep(2500);
		System.out.println("----------Seleccion de Plan -------------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.xpath("//*[@id='frmCatProductos:j_id2']/div[2]")).click();
		Thread.sleep(1500);
		File scrFile3 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile3, new File("d:\\Evidencias_Automatizacion\\Valora\\Seleccion Plan.png"));
		controlador.findElement(By.xpath("//*[@id='frmCatProductos:cmdNext']/div")).click();
		Thread.sleep(1500);
		System.out.println("------Ingresando Datos Contratante-------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.id("frmAsegurado:inputNombre")).sendKeys("Valora");
		controlador.findElement(By.id("frmAsegurado:inputAPaterno")).sendKeys("Test");
		controlador.findElement(By.id("frmAsegurado:inputAMaterno")).sendKeys("Test");
		controlador.findElement(By.id("frmAsegurado:popupfhNac_input")).sendKeys("31/05/1988");
		controlador.findElement(By.id("frmAsegurado:inputRFC")).sendKeys("SAMA8805314A0");
		controlador.findElement(By.id("frmAsegurado:inputTelefono")).sendKeys("5511235813");
		controlador.findElement(By.id("frmAsegurado:inputEMail")).sendKeys("test@test.com");
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:radioSexo']/tbody/tr/td[1]/div/div[2]")).click();
		controlador.findElement(By.id("frmAsegurado:inputCalle")).sendKeys("Gomas");
		controlador.findElement(By.id("frmAsegurado:inputNumExt")).sendKeys("61");
		controlador.findElement(By.id("frmAsegurado:inputCP")).sendKeys("08100"); 
		controlador.findElement(By.id("frmAsegurado:inputNumInt")).click();
		Thread.sleep(4000);
		controlador.findElement(By.id("frmAsegurado:menuEstados_label")).click();
		Thread.sleep(4000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuEstados_panel']/div/ul/li[2]")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmAsegurado:menuMunicipios_label")).click();
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuMunicipios_panel']/div/ul/li[2]")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmAsegurado:menuColonias_label")).click();
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuColonias_panel']/div/ul/li[2]")).click();
		File scrFile4 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile4, new File("d:\\Evidencias_Automatizacion\\Valora\\Datos del Contratante.png"));
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:btnAsegNext']/div")).click();
		System.out.println("------Ingresando Medio de Pago-----------");
		System.out.println("-----------------------------------------");
		Thread.sleep(4000);
		controlador.findElement(By.id("frmCobros:menuMediosCobro_label")).click();
		Thread.sleep(1000);
		controlador.findElement(By.xpath("//*[@id='frmCobros:menuMediosCobro_panel']/div/ul/li[2]")).click();
		Thread.sleep(1500);
		controlador.findElement(By.id("frmCobros:inputTHab")).sendKeys("Valora Test Test");
		controlador.findElement(By.id("frmCobros:inputNuTarjeta")).sendKeys("012546465465464465");
		controlador.findElement(By.id("frmCobros:menuBancos_label")).click();
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmCobros:menuBancos_panel']/div/ul/li[2]")).click();
		File scrFile5 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile5, new File("d:\\Evidencias_Automatizacion\\Valora\\Medio de Pago.png"));
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmCobros:cmdNext']/div")).click();
		File scrFile05 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile05, new File("d:\\Evidencias_Automatizacion\\Valora\\Medio de Pago_1.png"));
		Thread.sleep(2000);
		System.out.println("----------Confirmacion de Datos----------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.id("formVentaConfirm:aceptaDatos")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmValidate:Btnconfirmar")).click();
		Thread.sleep(4000);
		File scrFile6 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile6, new File("d:\\Evidencias_Automatizacion\\Valora\\Tramite Exitoso Plan 1.png"));
		controlador.findElement(By.id("frmVenta:cmdPrint")).click();
		System.out.println("--------------Venta Exitosa--------------");
		System.out.println("--------------Cuenta Clabe --------------");
		Thread.sleep(10000);
		controlador.findElement(By.id("frmVenta:j_idt51")).click();
		Thread.sleep(2000);

		/*------------------------------- Tarjeta de Credito ---------------------------------------*/	
		System.out.println("-----------------------------------------");
		System.out.println("----------Seleccion de Producto----------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.xpath("//*[@id='frmWelcome']/div/table[1]/tbody/tr[1]/td/a/div")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmSelectProductos:selectProducto_label")).click();
		Thread.sleep(500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:selectProducto_panel']/div/ul/li[2]")).click();
		Thread.sleep(1500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:canalSocioCanalVenta']/tbody/tr[3]/td[1]/div/div[2]")).click();
		File scrFile7 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile7, new File("d:\\Evidencias_Automatizacion\\Valora\\Seleccion Producto Plan 2.png"));
		Thread.sleep(1500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:cmdNext']/div")).click();
		Thread.sleep(2500);
		System.out.println("----------Seleccion de Plan 2------------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.xpath("//*[@id='frmCatProductos:j_id3']/div[2]")).click();
		Thread.sleep(1500);
		File scrFile8 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile8, new File("d:\\Evidencias_Automatizacion\\Valora\\Seleccion Plan 2.png"));
		controlador.findElement(By.xpath("//*[@id='frmCatProductos:cmdNext']/div")).click();
		Thread.sleep(1500);
		System.out.println("------Ingresando Datos Contratante-------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.id("frmAsegurado:inputNombre")).sendKeys("Valora");
		controlador.findElement(By.id("frmAsegurado:inputAPaterno")).sendKeys("Test");
		controlador.findElement(By.id("frmAsegurado:inputAMaterno")).sendKeys("Test");
		controlador.findElement(By.id("frmAsegurado:popupfhNac_input")).sendKeys("31/05/1988");
		controlador.findElement(By.id("frmAsegurado:inputRFC")).sendKeys("SAMA8805314A0");
		controlador.findElement(By.id("frmAsegurado:inputTelefono")).sendKeys("5511235813");
		controlador.findElement(By.id("frmAsegurado:inputEMail")).sendKeys("test@test.com");
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:radioSexo']/tbody/tr/td[1]/div/div[2]")).click();
		controlador.findElement(By.id("frmAsegurado:inputCalle")).sendKeys("Gomas");
		controlador.findElement(By.id("frmAsegurado:inputNumExt")).sendKeys("61");
		controlador.findElement(By.id("frmAsegurado:inputCP")).sendKeys("08100"); 
		controlador.findElement(By.id("frmAsegurado:inputNumInt")).click();
		Thread.sleep(4000);
		controlador.findElement(By.id("frmAsegurado:menuEstados_label")).click();
		Thread.sleep(4000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuEstados_panel']/div/ul/li[2]")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmAsegurado:menuMunicipios_label")).click();
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuMunicipios_panel']/div/ul/li[2]")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmAsegurado:menuColonias_label")).click();
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuColonias_panel']/div/ul/li[2]")).click();
		File scrFile9 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile9, new File("d:\\Evidencias_Automatizacion\\Valora\\Datos del Contratante Plan 2.png"));
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:btnAsegNext']/div")).click();
		System.out.println("------Ingresando Medio de Pago-----------");
		System.out.println("-----------------------------------------");
		Thread.sleep(4000);
		controlador.findElement(By.id("frmCobros:menuMediosCobro_label")).click();
		Thread.sleep(1000);
		controlador.findElement(By.xpath("//*[@id='frmCobros:menuMediosCobro_panel']/div/ul/li[3]")).click();
		Thread.sleep(1500);
		controlador.findElement(By.id("frmCobros:inputTHab")).sendKeys("Valora Test Test");
		controlador.findElement(By.id("frmCobros:inputNuTarjetaF")).sendKeys("4152");
		controlador.findElement(By.id("frmCobros:inputNuTarjetaS")).sendKeys("0000");
		controlador.findElement(By.id("frmCobros:inputNuTarjetaT")).sendKeys("6632");
		controlador.findElement(By.id("frmCobros:inputNuTarjetaL")).sendKeys("5125");
		controlador.findElement(By.id("frmCobros:inputFHVenc")).click();
		controlador.findElement(By.id("frmCobros:inputFHVenc")).sendKeys("08/2022");
		controlador.findElement(By.id("frmCobros:codSeg")).sendKeys("123");
		Thread.sleep(2000);
		File scrFile10 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile10, new File("d:\\Evidencias_Automatizacion\\Valora\\Medio de Pago Plan 2.png"));
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmCobros:cmdNext']/div")).click();
		File scrFile11 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile11, new File("d:\\Evidencias_Automatizacion\\Valora\\Medio de Pago_1 Plan 2.png"));
		Thread.sleep(2000);
		System.out.println("----------Confirmacion de Datos----------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.id("formVentaConfirm:aceptaDatos")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmValidate:Btnconfirmar")).click();
		Thread.sleep(4000);
		File scrFile12 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile12, new File("d:\\Evidencias_Automatizacion\\Valora\\Tramite Exitoso Plan 2.png"));
		controlador.findElement(By.id("frmVenta:cmdPrint")).click();
		System.out.println("------------Venta Exitosa 2--------------");
		System.out.println("------------Tarjeta de Debito--------------");
		Thread.sleep(10000);
		controlador.findElement(By.id("frmVenta:j_idt51")).click();
		Thread.sleep(2000);
		
		/*------------------------------- Tarjeta de Debito ---------------------------------------*/	
		System.out.println("-----------------------------------------");
		System.out.println("----------Seleccion de Producto----------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.xpath("//*[@id='frmWelcome']/div/table[1]/tbody/tr[1]/td/a/div")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmSelectProductos:selectProducto_label")).click();
		Thread.sleep(500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:selectProducto_panel']/div/ul/li[2]")).click();
		Thread.sleep(1500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:canalSocioCanalVenta']/tbody/tr[3]/td[1]/div/div[2]")).click();
		File scrFile13 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile13, new File("d:\\Evidencias_Automatizacion\\Valora\\Seleccion Producto Plan 3.png"));
		Thread.sleep(1500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:cmdNext']/div")).click();
		Thread.sleep(2500);
		System.out.println("----------Seleccion de Plan 3------------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.xpath("//*[@id='frmCatProductos:j_id4']/div[2]")).click();
		Thread.sleep(1500);
		File scrFile14 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile14, new File("d:\\Evidencias_Automatizacion\\Valora\\Seleccion Plan 3.png"));
		controlador.findElement(By.xpath("//*[@id='frmCatProductos:cmdNext']/div")).click();
		Thread.sleep(1500);
		System.out.println("------Ingresando Datos Contratante-------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.id("frmAsegurado:inputNombre")).sendKeys("Valora");
		controlador.findElement(By.id("frmAsegurado:inputAPaterno")).sendKeys("Test");
		controlador.findElement(By.id("frmAsegurado:inputAMaterno")).sendKeys("Test");
		controlador.findElement(By.id("frmAsegurado:popupfhNac_input")).sendKeys("31/05/1988");
		controlador.findElement(By.id("frmAsegurado:inputRFC")).sendKeys("SAMA8805314A0");
		controlador.findElement(By.id("frmAsegurado:inputTelefono")).sendKeys("5511235813");
		controlador.findElement(By.id("frmAsegurado:inputEMail")).sendKeys("test@test.com");
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:radioSexo']/tbody/tr/td[1]/div/div[2]")).click();
		controlador.findElement(By.id("frmAsegurado:inputCalle")).sendKeys("Gomas");
		controlador.findElement(By.id("frmAsegurado:inputNumExt")).sendKeys("61");
		controlador.findElement(By.id("frmAsegurado:inputCP")).sendKeys("08100"); 
		controlador.findElement(By.id("frmAsegurado:inputNumInt")).click();
		Thread.sleep(4000);
		controlador.findElement(By.id("frmAsegurado:menuEstados_label")).click();
		Thread.sleep(4000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuEstados_panel']/div/ul/li[2]")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmAsegurado:menuMunicipios_label")).click();
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuMunicipios_panel']/div/ul/li[2]")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmAsegurado:menuColonias_label")).click();
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuColonias_panel']/div/ul/li[2]")).click();
		
		File scrFile15 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile15, new File("d:\\Evidencias_Automatizacion\\Valora\\Datos del Contratante Plan 3.png"));
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:btnAsegNext']/div")).click();
		System.out.println("------Ingresando Medio de Pago-----------");
		System.out.println("-----------------------------------------");
		Thread.sleep(4000);
		controlador.findElement(By.id("frmCobros:menuMediosCobro_label")).click();
		Thread.sleep(1000);
		controlador.findElement(By.xpath("//*[@id='frmCobros:menuMediosCobro_panel']/div/ul/li[4]")).click();
		Thread.sleep(1500);
		controlador.findElement(By.id("frmCobros:inputTHab")).sendKeys("Valora Test Test");
		controlador.findElement(By.id("frmCobros:inputNuTarjetaF")).sendKeys("4152");
		controlador.findElement(By.id("frmCobros:inputNuTarjetaS")).sendKeys("0000");
		controlador.findElement(By.id("frmCobros:inputNuTarjetaT")).sendKeys("6632");
		controlador.findElement(By.id("frmCobros:inputNuTarjetaL")).sendKeys("5125");
		controlador.findElement(By.id("frmCobros:inputFHVenc")).click();
		controlador.findElement(By.id("frmCobros:inputFHVenc")).sendKeys("08/2022");
		controlador.findElement(By.id("frmCobros:codSeg")).sendKeys("123");
		Thread.sleep(2000);
		File scrFile16 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile16, new File("d:\\Evidencias_Automatizacion\\Valora\\Medio de Pago Plan 3.png"));
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmCobros:cmdNext']/div")).click();
		File scrFile17 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile17, new File("d:\\Evidencias_Automatizacion\\Valora\\Medio de Pago_1 Plan 3.png"));
		Thread.sleep(2000);
		System.out.println("----------Confirmacion de Datos----------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.id("formVentaConfirm:aceptaDatos")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmValidate:Btnconfirmar")).click();
		Thread.sleep(4000);
		File scrFile18 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile18, new File("d:\\Evidencias_Automatizacion\\Valora\\Tramite Exitoso Plan 3.png"));
		controlador.findElement(By.id("frmVenta:cmdPrint")).click();
		System.out.println("--------------Venta Exitosa--------------");
		System.out.println("--------------Tarjeta de Debito-------------");
		Thread.sleep(10000);
		controlador.findElement(By.id("frmVenta:j_idt51")).click();
	}


    public void Venta_VW_Bank_Usados (ChromeDriver controlador, String producto) throws Exception {
		
		
		
		System.out.println("-----------------------------------------");
		System.out.println("---------Ingresando a Posnet UAT---------");
		System.out.println("-----------------------------------------");
		controlador.get("https://cardifonline-uat.com.mx/posnet/login.jsf#");
		System.out.println("-----------------------------------------");
		File scrFile = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile, new File("d:\\Evidencias_Automatizacion\\Momentos\\Inicio Login.png"));
		Thread.sleep(1000);
		System.out.println("----------Ingresando Usuario-------------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.name("j_idt26")).sendKeys("2014042829");
		Thread.sleep(1000);
		System.out.println("---------Ingresando Contraseña-----------");
		controlador.findElement(By.name("j_idt30")).sendKeys("Cardif123#");
		File scrFile01 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile01, new File("d:\\Evidencias_Automatizacion\\Momentos\\Inicio Login.png"));
		controlador.findElement(By.id("j_idt34")).click();
		Thread.sleep(1500);
		System.out.println("-----------------------------------------");
		System.out.println("------------Conexion exitosa-------------");
		File scrFile1 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile1, new File("d:\\Evidencias_Automatizacion\\Momentos\\Conexion_exitosa.png"));
		System.out.println("-----------------------------------------");
		System.out.println("----------Seleccion de Producto----------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.xpath("//*[@id='frmWelcome']/div/table[1]/tbody/tr[1]/td/a/div")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmSelectProductos:selectProducto_label")).click();
		Thread.sleep(500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:selectProducto_panel']/div/ul/li[3]")).click();
		Thread.sleep(1500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:canalSocioCanalVenta']/tbody/tr[3]/td[1]/div/div[2]")).click();
		File scrFile2 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile2, new File("d:\\Evidencias_Automatizacion\\Momentos\\Seleccion Producto.png"));
		Thread.sleep(1500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:cmdNext']/div")).click();
		Thread.sleep(2500);
		System.out.println("----------Seleccion de Plan -------------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.xpath("//*[@id='frmCatProductos:j_id2']/div[2]")).click();
		Thread.sleep(1500);
		File scrFile3 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile3, new File("d:\\Evidencias_Automatizacion\\Momentos\\Seleccion Plan.png"));
		controlador.findElement(By.xpath("//*[@id='frmCatProductos:cmdNext']/div")).click();
		Thread.sleep(1500);
		System.out.println("------Ingresando Datos Contratante-------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.id("frmAsegurado:inputNombre")).sendKeys("Momentos");
		controlador.findElement(By.id("frmAsegurado:inputAPaterno")).sendKeys("Test");
		controlador.findElement(By.id("frmAsegurado:inputAMaterno")).sendKeys("Test");
		controlador.findElement(By.id("frmAsegurado:popupfhNac_input")).sendKeys("31/05/1988");
		controlador.findElement(By.id("frmAsegurado:inputRFC")).sendKeys("SAMA8805314A0");
		controlador.findElement(By.id("frmAsegurado:inputTelefono")).sendKeys("5511235813");
		controlador.findElement(By.id("frmAsegurado:inputEMail")).sendKeys("test@test.com");
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:radioSexo']/tbody/tr/td[1]/div/div[2]")).click();
		controlador.findElement(By.id("frmAsegurado:inputCalle")).sendKeys("Gomas");
		controlador.findElement(By.id("frmAsegurado:inputNumExt")).sendKeys("61");
		controlador.findElement(By.id("frmAsegurado:inputCP")).sendKeys("08100"); 
		controlador.findElement(By.id("frmAsegurado:inputNumInt")).click();
		Thread.sleep(4000);
		controlador.findElement(By.id("frmAsegurado:menuEstados_label")).click();
		Thread.sleep(4000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuEstados_panel']/div/ul/li[2]")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmAsegurado:menuMunicipios_label")).click();
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuMunicipios_panel']/div/ul/li[2]")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmAsegurado:menuColonias_label")).click();
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuColonias_panel']/div/ul/li[2]")).click();
		File scrFile4 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile4, new File("d:\\Evidencias_Automatizacion\\Momentos\\Datos del Contratante.png"));
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:btnAsegNext']/div")).click();
		System.out.println("------Ingresando Medio de Pago-----------");
		System.out.println("-----------------------------------------");
		Thread.sleep(4000);
		controlador.findElement(By.id("frmCobros:menuMediosCobro_label")).click();
		Thread.sleep(1000);
		controlador.findElement(By.xpath("//*[@id='frmCobros:menuMediosCobro_panel']/div/ul/li[2]")).click();
		Thread.sleep(1500);
		controlador.findElement(By.id("frmCobros:inputTHab")).sendKeys("Momentos Test Test");
		controlador.findElement(By.id("frmCobros:inputNuTarjeta")).sendKeys("012546465465464465");
		controlador.findElement(By.id("frmCobros:menuBancos_label")).click();
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmCobros:menuBancos_panel']/div/ul/li[2]")).click();
		File scrFile5 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile5, new File("d:\\Evidencias_Automatizacion\\Momentos\\Medio de Pago.png"));
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmCobros:cmdNext']/div")).click();
		File scrFile05 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile05, new File("d:\\Evidencias_Automatizacion\\Momentos\\Medio de Pago_1.png"));
		Thread.sleep(2000);
		System.out.println("----------Confirmacion de Datos----------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.id("formVentaConfirm:aceptaDatos")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmValidate:Btnconfirmar")).click();
		Thread.sleep(4000);
		File scrFile6 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile6, new File("d:\\Evidencias_Automatizacion\\Momentos\\Tramite Exitoso Plan 1.png"));
		controlador.findElement(By.id("frmVenta:cmdPrint")).click();
		System.out.println("--------------Venta Exitosa--------------");
		System.out.println("--------------Cuenta Clabe --------------");
		Thread.sleep(10000);
		controlador.findElement(By.id("frmVenta:j_idt51")).click();
		Thread.sleep(2000);

		/*--------------------------------------------*/	
		System.out.println("-----------------------------------------");
		System.out.println("----------Seleccion de Producto----------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.xpath("//*[@id='frmWelcome']/div/table[1]/tbody/tr[1]/td/a/div")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmSelectProductos:selectProducto_label")).click();
		Thread.sleep(500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:selectProducto_panel']/div/ul/li[3]")).click();
		Thread.sleep(1500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:canalSocioCanalVenta']/tbody/tr[3]/td[1]/div/div[2]")).click();
		File scrFile7 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile7, new File("d:\\Evidencias_Automatizacion\\Momentos\\Seleccion Producto Plan 2.png"));
		Thread.sleep(1500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:cmdNext']/div")).click();
		Thread.sleep(2500);
		System.out.println("----------Seleccion de Plan 2------------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.xpath("//*[@id='frmCatProductos:j_id3']/div[2]")).click();
		Thread.sleep(1500);
		File scrFile8 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile8, new File("d:\\Evidencias_Automatizacion\\Momentos\\Seleccion Plan 2.png"));
		controlador.findElement(By.xpath("//*[@id='frmCatProductos:cmdNext']/div")).click();
		Thread.sleep(1500);
		System.out.println("------Ingresando Datos Contratante-------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.id("frmAsegurado:inputNombre")).sendKeys("Momentos");
		controlador.findElement(By.id("frmAsegurado:inputAPaterno")).sendKeys("Test");
		controlador.findElement(By.id("frmAsegurado:inputAMaterno")).sendKeys("Test");
		controlador.findElement(By.id("frmAsegurado:popupfhNac_input")).sendKeys("31/05/1988");
		controlador.findElement(By.id("frmAsegurado:inputRFC")).sendKeys("SAMA8805314A0");
		controlador.findElement(By.id("frmAsegurado:inputTelefono")).sendKeys("5511235813");
		controlador.findElement(By.id("frmAsegurado:inputEMail")).sendKeys("test@test.com");
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:radioSexo']/tbody/tr/td[1]/div/div[2]")).click();
		controlador.findElement(By.id("frmAsegurado:inputCalle")).sendKeys("Gomas");
		controlador.findElement(By.id("frmAsegurado:inputNumExt")).sendKeys("61");
		controlador.findElement(By.id("frmAsegurado:inputCP")).sendKeys("08100"); 
		controlador.findElement(By.id("frmAsegurado:inputNumInt")).click();
		Thread.sleep(4000);
		controlador.findElement(By.id("frmAsegurado:menuEstados_label")).click();
		Thread.sleep(4000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuEstados_panel']/div/ul/li[2]")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmAsegurado:menuMunicipios_label")).click();
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuMunicipios_panel']/div/ul/li[2]")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmAsegurado:menuColonias_label")).click();
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuColonias_panel']/div/ul/li[2]")).click();
		File scrFile9 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile9, new File("d:\\Evidencias_Automatizacion\\Momentos\\Datos del Contratante Plan 2.png"));
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:btnAsegNext']/div")).click();
		System.out.println("------Ingresando Medio de Pago-----------");
		System.out.println("-----------------------------------------");
		Thread.sleep(4000);
		controlador.findElement(By.id("frmCobros:menuMediosCobro_label")).click();
		Thread.sleep(1000);
		controlador.findElement(By.xpath("//*[@id='frmCobros:menuMediosCobro_panel']/div/ul/li[3]")).click();
		Thread.sleep(1500);
		controlador.findElement(By.id("frmCobros:inputTHab")).sendKeys("Momentos Test Test");
		controlador.findElement(By.id("frmCobros:inputNuTarjetaF")).sendKeys("4152");
		controlador.findElement(By.id("frmCobros:inputNuTarjetaS")).sendKeys("0000");
		controlador.findElement(By.id("frmCobros:inputNuTarjetaT")).sendKeys("6632");
		controlador.findElement(By.id("frmCobros:inputNuTarjetaL")).sendKeys("5125");
		controlador.findElement(By.id("frmCobros:inputFHVenc")).click();
		controlador.findElement(By.id("frmCobros:inputFHVenc")).sendKeys("08/2022");
		controlador.findElement(By.id("frmCobros:codSeg")).sendKeys("123");
		Thread.sleep(2000);
		File scrFile10 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile10, new File("d:\\Evidencias_Automatizacion\\Momentos\\Medio de Pago Plan 2.png"));
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmCobros:cmdNext']/div")).click();
		File scrFile11 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile11, new File("d:\\Evidencias_Automatizacion\\Momentos\\Medio de Pago_1 Plan 2.png"));
		Thread.sleep(2000);
		System.out.println("----------Confirmacion de Datos----------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.id("formVentaConfirm:aceptaDatos")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmValidate:Btnconfirmar")).click();
		Thread.sleep(4000);
		File scrFile12 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile12, new File("d:\\Evidencias_Automatizacion\\Momentos\\Tramite Exitoso Plan 2.png"));
		controlador.findElement(By.id("frmVenta:cmdPrint")).click();
		System.out.println("--------------Venta Exitosa--------------");
		System.out.println("------------Tarjeta de Credito-----------");
		Thread.sleep(10000);
		controlador.findElement(By.id("frmVenta:j_idt51")).click();
		Thread.sleep(2000);
		
		/*--------------------------------------------*/	
		System.out.println("-----------------------------------------");
		System.out.println("----------Seleccion de Producto----------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.xpath("//*[@id='frmWelcome']/div/table[1]/tbody/tr[1]/td/a/div")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmSelectProductos:selectProducto_label")).click();
		Thread.sleep(500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:selectProducto_panel']/div/ul/li[3]")).click();
		Thread.sleep(1500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:canalSocioCanalVenta']/tbody/tr[3]/td[1]/div/div[2]")).click();
		File scrFile13 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile13, new File("d:\\Evidencias_Automatizacion\\Momentos\\Seleccion Producto Plan 3.png"));
		Thread.sleep(1500);
		controlador.findElement(By.xpath("//*[@id='frmSelectProductos:cmdNext']/div")).click();
		Thread.sleep(2500);
		System.out.println("----------Seleccion de Plan 3------------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.xpath("//*[@id='frmCatProductos:j_id4']/div[2]")).click();
		Thread.sleep(1500);
		File scrFile14 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile14, new File("d:\\Evidencias_Automatizacion\\Momentos\\Seleccion Plan 3.png"));
		controlador.findElement(By.xpath("//*[@id='frmCatProductos:cmdNext']/div")).click();
		Thread.sleep(1500);
		System.out.println("------Ingresando Datos Contratante-------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.id("frmAsegurado:inputNombre")).sendKeys("Momentos");
		controlador.findElement(By.id("frmAsegurado:inputAPaterno")).sendKeys("Test");
		controlador.findElement(By.id("frmAsegurado:inputAMaterno")).sendKeys("Test");
		controlador.findElement(By.id("frmAsegurado:popupfhNac_input")).sendKeys("31/05/1988");
		controlador.findElement(By.id("frmAsegurado:inputRFC")).sendKeys("SAMA8805314A0");
		controlador.findElement(By.id("frmAsegurado:inputTelefono")).sendKeys("5511235813");
		controlador.findElement(By.id("frmAsegurado:inputEMail")).sendKeys("test@test.com");
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:radioSexo']/tbody/tr/td[1]/div/div[2]")).click();
		controlador.findElement(By.id("frmAsegurado:inputCalle")).sendKeys("Gomas");
		controlador.findElement(By.id("frmAsegurado:inputNumExt")).sendKeys("61");
		controlador.findElement(By.id("frmAsegurado:inputCP")).sendKeys("08100"); 
		controlador.findElement(By.id("frmAsegurado:inputNumInt")).click();
		Thread.sleep(4000);
		controlador.findElement(By.id("frmAsegurado:menuEstados_label")).click();
		Thread.sleep(4000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuEstados_panel']/div/ul/li[2]")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmAsegurado:menuMunicipios_label")).click();
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuMunicipios_panel']/div/ul/li[2]")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmAsegurado:menuColonias_label")).click();
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:menuColonias_panel']/div/ul/li[2]")).click();
		
		File scrFile15 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile15, new File("d:\\Evidencias_Automatizacion\\Momentos\\Datos del Contratante Plan 3.png"));
		controlador.findElement(By.xpath("//*[@id='frmAsegurado:btnAsegNext']/div")).click();
		System.out.println("------Ingresando Medio de Pago-----------");
		System.out.println("-----------------------------------------");
		Thread.sleep(4000);
		controlador.findElement(By.id("frmCobros:menuMediosCobro_label")).click();
		Thread.sleep(1000);
		controlador.findElement(By.xpath("//*[@id='frmCobros:menuMediosCobro_panel']/div/ul/li[4]")).click();
		Thread.sleep(1500);
		controlador.findElement(By.id("frmCobros:inputTHab")).sendKeys("Momentos Test Test");
		controlador.findElement(By.id("frmCobros:inputNuTarjetaF")).sendKeys("4152");
		controlador.findElement(By.id("frmCobros:inputNuTarjetaS")).sendKeys("0000");
		controlador.findElement(By.id("frmCobros:inputNuTarjetaT")).sendKeys("6632");
		controlador.findElement(By.id("frmCobros:inputNuTarjetaL")).sendKeys("5125");
		controlador.findElement(By.id("frmCobros:inputFHVenc")).click();
		controlador.findElement(By.id("frmCobros:inputFHVenc")).sendKeys("08/2022");
		controlador.findElement(By.id("frmCobros:codSeg")).sendKeys("123");
		Thread.sleep(2000);
		File scrFile16 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile16, new File("d:\\Evidencias_Automatizacion\\Momentos\\Medio de Pago Plan 3.png"));
		Thread.sleep(2000);
		controlador.findElement(By.xpath("//*[@id='frmCobros:cmdNext']/div")).click();
		File scrFile17 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile17, new File("d:\\Evidencias_Automatizacion\\Momentos\\Medio de Pago_1 Plan 3.png"));
		Thread.sleep(2000);
		System.out.println("----------Confirmacion de Datos----------");
		System.out.println("-----------------------------------------");
		controlador.findElement(By.id("formVentaConfirm:aceptaDatos")).click();
		Thread.sleep(2000);
		controlador.findElement(By.id("frmValidate:Btnconfirmar")).click();
		Thread.sleep(4000);
		File scrFile18 = ((TakesScreenshot)controlador).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile18, new File("d:\\Evidencias_Automatizacion\\Momentos\\Tramite Exitoso Plan 3.png"));
		controlador.findElement(By.id("frmVenta:cmdPrint")).click();
		System.out.println("--------------Venta Exitosa--------------");
		System.out.println("------------Tarjeta de Debito------------");
		Thread.sleep(10000);
		controlador.findElement(By.id("frmVenta:j_idt51")).click();
	}



	
    
}	